<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<script>
    window.dataLayer = [
        {'event': 'gtm.js', 'gtm.start': new Date().getTime()},
        {'event': 'error', 'error.code': 503}
    ];
</script>
<script src="https://www.googletagmanager.com/gtm.js?id=GTM-TWSPHGQ" async></script>

<style>
    body { color: #333; background: white; width: 500px; margin: 100px auto }
    h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
    p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
</style>

<title>Stránka je dočasně nedostupná.</title>

<h1>Omlouváme se</h1>

<p>Stránka je dočasně nedostupná, protože na ni probíhá právě údržba. Zkuste to proím za chvíli.</p>
