version: '3'
services:
    web:
        image: jakubboucek/lamp-devstack-php:7.3-debug
        ports:
            - "8000:80"
        volumes:
            - ".:/var/www/html"
        restart: always
        environment:
            NETTE_DEBUG: 1
            XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost"
        depends_on:
            - mysqldb
    mysqldb:
        image: jakubboucek/lamp-devstack-mysql:10.4
        container_name: zlinskybarcampweb_mysqldb_1
        restart: always
        ports:
            - "8686:3306"
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=zlinskybarcamp
            - MYSQL_ROOT_PASSWORD=redbitmasters
